### ISSUE TITLE
error probably related to rtlcss

### ISSUE THREAD

**Issue by hamid07ss** [romainberger/webpack-rtl-plugin#29]
(node:9468) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

**Comment by romainberger** [comment]
Can you confirm the version of webpack you're using? This kind of error appear with webpack 4, and this plugin is not yet working with this version.

**Comment by hamid07ss** [comment]
```
"webpack": "4.28.3",
"webpack-rtl-plugin": "^1.8.2",
```

yes, my webpack version is 4

**Comment by romainberger** [comment]
Alright, I'll try to update the plugin to make it compatible with webpack 4, hopefully today or tomorrow.

**Comment by hamid07ss** [comment]
thanks so much

**Comment by romainberger** [comment]
I just published v2 which is compatible with webpack 4. Please let me know if you have any issue.
Thanks!
